#!/usr/bin/expect

set ip [lindex $argv 0]

#set user [lindex $argv 1]

#set Password [lindex $argv 2]
set prompt ":|#|\\\$"
spawn ssh "root@192.168.1.$ip"
expect {
"(yes/no)" { send "yes\r"; exp_continue }
"password:" { send "youpassword\r" }
}

interact -o -nobuffer -re $prompt return
#send "ifconfig\r"
send "service salt-minion restart && chkconfig salt-minion on\r"
interact -o -nobuffer -re $prompt return
send "exit\r"
interact

